### PR TITLE
update to nushell version 0.86.1

### PR DESCRIPTION
**Pull request by fdncred**
This is just a friendly update to move the code to the latest nushell syntax version 0.86.1.

### CODE REVIEW

**Comment by Taywee** [comment]
Nice!  Thanks for the PR!

**Comment by Taywee** [comment]
Looks like 0.86.1 isn't released yet.  I'll adjust this to use 0.86.0 until 0.86.1 releases.

**Comment by fdncred** [comment]
0.86.1 will turn into 0.87.0 on Nov 14th. I don't believe the new syntax will work in 0.86.0 though. Just trying to help people learn the new record syntax.

**Comment by Taywee** [comment]
Ah, for sure.  Thanks.  I'll try to keep it up to date.  I've stopped using nushell for now, because I have a lot of files with special characters like square brackets, and [commands doing their own globbing](https://github.com/nushell/nushell/discussions/6066#discussioncomment-6880660) has caused me to lose some files I didn't want to (I had a file called `*.opus` and I didn't realize it until I had deleted much more than I wanted to).

**Comment by fdncred** [comment]
Yup, that PR helps quite a bit. I understand your position though. Currently there isn't an override for globbing. However, you can configure nushell to always rm to the trash can so things aren't lost by accident.

**Pull request merged**
